### ISSUE TITLE
Broken slack invite link in docs

### ISSUE THREAD

**Issue by rbtcollins** [emissary-ingress/community#6]
[This page](https://www.getambassador.io/docs/emissary/latest/about/faq/) has a link to https://a8r.io/Slack - it leads to an invite that requires a datawire email address (even if you try Google integration etc).

[This page](https://www.getambassador.io/contact-us/) has a link to https://a8r.io/slack - it leads to an invite that allows anyone in the world to sign up.

Not sure if this is the right place to file it, but perhaps you can refile it if wrong.

**Comment by LanceEa** [comment]
The channel is now hosted in the CNCF slack and the readme has been updated making this issue no longer valid.
